[connections.snowflake]
account = "LFAQUDB-HF93281"
user = "vaibhavk"
password = "King@4424"
role = "accountadmin"
warehouse = "vaibhav"
database = "MANGO_LEAF_ML_DB"
schema = "ML_APP_SCHEMA"
client_session_keep_alive = true
