[connections.snowflake]
account = "LFAQUDB-HF93281"
user = "vaibhavk"
password = "King@4424"
role = "accountadmin"
warehouse = "vaibhav"
database = "PETS"
schema = "PUBLIC"
client_session_keep_alive = true
